apiVersion: v1
data:
  prometheus.yml: "# my global config\r\r\nglobal:\r\r\n  scrape_interval:     15s
    # Set the scrape interval to every 15 seconds. Default is every 1 minute.\r\r\n
    \ evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every
    1 minute.\r\r\n  # scrape_timeout is set to the global default (10s).\r\r\n\r\r\n#
    Alertmanager configuration\r\r\nalerting:\r\r\n  alertmanagers:\r\r\n  - static_configs:\r\r\n
    \   - targets:\r\r\n      # - alertmanager:9093\r\r\n\r\r\n# Load rules once and
    periodically evaluate them according to the global 'evaluation_interval'.\r\r\nrule_files:\r\r\n
    \ # - \"first_rules.yml\"\r\r\n  # - \"second_rules.yml\"\r\r\n\r\r\n# A scrape
    configuration containing exactly one endpoint to scrape:\r\r\n# Here it's Prometheus
    itself.\r\r\nscrape_configs:\r\r\n  # The job name is added as a label `job=<job_name>`
    to any timeseries scraped from this config.\r\r\n  - job_name: 'prometheus'\r\r\n\r\r\n
    \   # metrics_path defaults to '/metrics'\r\r\n    # scheme defaults to 'http'.\r\r\n\r\r\n
    \   static_configs:\r\r\n    - targets: ['localhost:9090','192.168.11.11:9100','192.168.11.12:9100','192.168.11.13:9100']\r\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
