apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
  name: prometheus-pv  
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /rjj-storage/k3s/prometheus
    server: 192.168.11.13
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
